from __future__ import annotations

from datetime import date
from .models import CandidateProfile, Recruitment, RecruitmentPost, SourceDocument

RECRUITMENTS: list[Recruitment] = [
    Recruitment(
        id="recruitment_ssc_cgl",
        organization_id="org_ssc",
        organization_name="Staff Selection Commission",
        title="SSC CGL Examination 2025-26",
        slug="ssc-cgl-2025",
        recruitment_type="EXAM",
        status="ACTIVE",
        published_at="2025-06-24T10:00:00Z",
        last_verified_at="2026-10-05T12:00:00Z",
        application_start_date=date(2025, 6, 24),
        application_deadline=date(2025, 7, 27),
        exam_date=date(2025, 9, 15),
        official_apply_url="https://ssc.gov.in/",
        required_education_level="GRADUATE",
        verification_status="VERIFIED",
        posts=[
            RecruitmentPost(
                id="post_ssc_cgl_tier1",
                title="Combined Graduate Level Group B & C Posts",
                department="Ministries & Departments of Govt. of India",
                job_family="Administrative & Inspection",
                location_type="All India",
                salary_min=35400,
                salary_max=142400,
                salary_text="Pay Level 4 to Level 7 (₹25,500 – ₹1,42,400)",
                vacancies=17727,
                description="Recruitment to various Group B and Group C posts in central ministries and subordinate offices.",
            )
        ],
        official_sources=[
            SourceDocument(
                id="doc_ssc_cgl_notice_2025",
                title="SSC CGL 2025 Official Notification (Notice No. 3/1/2024-P&P-I)",
                url="https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoard/Notice_CGL_2025.pdf",
                document_type="NOTIFICATION",
                version_number=1,
                page=7,
                section="Clause 5: Age Limit & Essential Qualification",
                verification_status="VERIFIED",
            ),
            SourceDocument(
                id="doc_ssc_portal",
                title="Staff Selection Commission official portal",
                url="https://ssc.gov.in/",
                document_type="OFFICIAL_PORTAL",
                version_number=1,
                verification_status="VERIFIED",
            ),
        ],
    ),
    Recruitment(
        id="recruitment_upsc_cse",
        organization_id="org_upsc",
        organization_name="Union Public Service Commission",
        title="UPSC Civil Services Examination (CSE) 2025",
        slug="upsc-cse-2025",
        recruitment_type="EXAM",
        status="ACTIVE",
        published_at="2025-01-22T10:00:00Z",
        last_verified_at="2026-10-05T12:00:00Z",
        application_start_date=date(2025, 1, 22),
        application_deadline=date(2025, 2, 11),
        exam_date=date(2025, 5, 25),
        official_apply_url="https://upsconline.nic.in/",
        required_education_level="GRADUATE",
        verification_status="VERIFIED",
        posts=[
            RecruitmentPost(
                id="post_upsc_cse_2025",
                title="Civil Services (IAS, IPS, IFS & Central Services)",
                department="Department of Personnel and Training",
                job_family="All India Services",
                location_type="All India",
                salary_min=56100,
                salary_max=250000,
                salary_text="Pay Level 10 (₹56,100 basic pay) up to Apex Scale",
                vacancies=1056,
                description="Indian Administrative Service, Indian Foreign Service, Indian Police Service and Central Services Group A & B.",
            )
        ],
        official_sources=[
            SourceDocument(
                id="doc_upsc_cse_notice_2025",
                title="UPSC Civil Services Rules 2025 (Gazette No. 01/2025-CSP)",
                url="https://upsc.gov.in/sites/default/files/Notification-CSP-2025-engl.pdf",
                document_type="NOTIFICATION",
                version_number=1,
                page=6,
                section="Section III: Eligibility Conditions",
                verification_status="VERIFIED",
            ),
        ],
    ),
    Recruitment(
        id="recruitment_ibps_po",
        organization_id="org_ibps",
        organization_name="Institute of Banking Personnel Selection",
        title="IBPS CRP PO/MT-XIV (Probationary Officers)",
        slug="ibps-po-xiv-2025",
        recruitment_type="EXAM",
        status="ACTIVE",
        published_at="2025-08-01T09:00:00Z",
        last_verified_at="2026-10-05T12:00:00Z",
        application_start_date=date(2025, 8, 1),
        application_deadline=date(2025, 8, 28),
        exam_date=date(2025, 10, 19),
        official_apply_url="https://ibps.in/",
        required_education_level="GRADUATE",
        verification_status="VERIFIED",
        posts=[
            RecruitmentPost(
                id="post_ibps_po_xiv",
                title="Probationary Officer / Management Trainee",
                department="Participating Public Sector Commercial Banks",
                job_family="Public Sector Banking",
                location_type="All India",
                salary_min=48170,
                salary_max=85000,
                salary_text="Scale I Officer (₹48,480 starting basic pay + allowances)",
                vacancies=3955,
                description="Selection of Probationary Officers in 11 participating public sector banks across India.",
            )
        ],
        official_sources=[
            SourceDocument(
                id="doc_ibps_po_xiv",
                title="IBPS Detailed Advertisement CRP PO/MT-XIV",
                url="https://www.ibps.in/crp-po-mt-xiv-notification.pdf",
                document_type="NOTIFICATION",
                version_number=1,
                page=4,
                section="Eligibility Criteria: Age & Education",
                verification_status="VERIFIED",
            ),
        ],
    ),
    Recruitment(
        id="recruitment_rrb_ntpc",
        organization_id="org_rrb",
        organization_name="Railway Recruitment Boards",
        title="RRB NTPC Graduate Level Posts (CEN 05/2024)",
        slug="rrb-ntpc-graduate-2024-25",
        recruitment_type="EXAM",
        status="ACTIVE",
        published_at="2024-09-14T10:00:00Z",
        last_verified_at="2026-10-05T12:00:00Z",
        application_start_date=date(2024, 9, 14),
        application_deadline=date(2024, 10, 20),
        exam_date=date(2025, 4, 10),
        official_apply_url="https://www.rrbapply.gov.in/",
        required_education_level="GRADUATE",
        verification_status="VERIFIED",
        posts=[
            RecruitmentPost(
                id="post_rrb_ntpc_grad",
                title="Station Master, Goods Train Manager, Chief Commercial Clerk",
                department="Ministry of Railways (All Zonal Railways)",
                job_family="Railway Operations",
                location_type="National",
                salary_min=29200,
                salary_max=92300,
                salary_text="Pay Level 5 & Level 6 (₹29,200 – ₹92,300)",
                vacancies=8113,
                description="Centralized Employment Notice for Graduate Posts in Indian Railways.",
            )
        ],
        official_sources=[
            SourceDocument(
                id="doc_rrb_ntpc_cen05",
                title="RRB Centralized Employment Notice CEN 05/2024",
                url="https://www.rrbapply.gov.in/documents/CEN_05_2024_NTPC_Grad.pdf",
                document_type="NOTIFICATION",
                version_number=1,
                page=8,
                section="Age Limit & Educational Qualifications",
                verification_status="VERIFIED",
            ),
        ],
    ),
    Recruitment(
        id="recruitment_tspsc_group1",
        organization_id="org_tspsc",
        organization_name="Telangana Public Service Commission",
        title="TSPSC Group-I Services Recruitment 2024-25",
        slug="tspsc-group-i-2024",
        recruitment_type="RECRUITMENT",
        status="ACTIVE",
        published_at="2024-02-23T11:00:00Z",
        last_verified_at="2026-10-05T12:00:00Z",
        application_start_date=date(2024, 2, 23),
        application_deadline=date(2024, 3, 14),
        exam_date=date(2024, 10, 21),
        official_apply_url="https://www.tspsc.gov.in/",
        required_education_level="GRADUATE",
        verification_status="VERIFIED",
        posts=[
            RecruitmentPost(
                id="post_tspsc_group1_2025",
                title="Deputy Collector, DSP, Commercial Tax Officer, RDO",
                department="Telangana State Civil Administration",
                job_family="State Civil Services",
                location_type="Telangana",
                salary_min=51320,
                salary_max=150000,
                salary_text="Pay Scale ₹51,320 – ₹1,50,000",
                vacancies=563,
                description="Direct recruitment to Group-I Services under Government of Telangana.",
            )
        ],
        official_sources=[
            SourceDocument(
                id="doc_tspsc_group1_notif",
                title="Telangana Public Service Commission Notification No. 02/2024",
                url="https://www.tspsc.gov.in/notifications/022024_GroupI.pdf",
                document_type="NOTIFICATION",
                version_number=1,
                page=5,
                section="Age & Educational Qualifications",
                verification_status="VERIFIED",
            ),
        ],
    ),
]

USER_PROFILE = CandidateProfile(
    user_id="user_123",
    date_of_birth="1995-06-12",
    category="GENERAL",
    domicile_state="Telangana",
    preferred_states=["Telangana", "India"],
    education_level="GRADUATE",
    degree_name="B.Tech",
    specialization="Computer Science",
    experience_years=2.0,
    gender="F",
)

SAVED_RECRUITMENT_IDS: list[str] = ["recruitment_tspsc_group1", "recruitment_ssc_cgl"]
REMINDERS: list[dict] = [
    {
        "id": "reminder_sample_1",
        "user_id": "user_123",
        "recruitment_id": "recruitment_ssc_cgl",
        "event_type": "DEADLINE",
        "scheduled_for": "2025-07-27T00:00:00",
        "persistence": "PERSISTED",
    }
]
